# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build='make'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
" if file was updated vista is automatically updated
let g:vista_update_on_text_changed = 1
let g:vista_default_executive = 'vim_lsp'
nnoremap <silent><Space>v : <C-u>Vista!!<CR>
'''

[[plugins]] #resize paines
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'twitvim/twitvim'
hook_add = '''
let twitvim_token_file = expand("~/.config/vim/.twitvim.token")
let twitvim_force_ssl = 1
let twitvim_count = 100
nnoremap <silent><Space>f : <C-u>FriendsTwitter<CR>
nnoremap <silent><Space>p : <C-u>PosttoTwitter<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends=['vimproc']
hook_add='''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
	\ 'runner'    : 'vimproc',
	\ 'runner/vimproc/updatetime' : 60,
	\ 'outputter' : 'error',
	\ 'outputter/error/success' : 'buffer',
	\ 'outputter/error/error'   : 'quickfix',
	\ 'outputter/buffer/split'  : ':rightbelow 8sp',
	\ 'outputter/buffer/close_on_empty' : 1,
	\ }
'''

# this is plugin for show git diff at left part
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = '''
" セルの区切り文字をVSCode互換の # %% に指定する
let g:jupytext_fmt = 'py:percent'

" vimのPython向けシンタックスハイライトを有効にする
let g:jupytext_filetype_map = {'py': 'python'}
'''

#[[plugins]]
#repo = 'jupyter-vim/jupyter-vim'
#hook_add = '''
#'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]] # for theme color
repo = 'tomasr/molokai'
hook_add = '''
colorscheme molokai
'''
